### ISSUE TITLE
A bug in postgresql12.9

### ISSUE THREAD

**Issue by liugang-sd** [okbob/session_exec#3]
From postgresql12.9,when 'session_exec' call a function like behind, will output a log "cannot execute SQL without an outer snapshot or portal", and the function can't execute.

create or replace function public.login() returns void as $$
declare
    res record;
    n_times constant int := 10;
    failed_login_times constant int := 5;
    failed_login integer;
begin
end;
$$ language plpgsql strict security definer set search_path to 'public';

**Comment by okbob** [comment]
Hi

út 22. 2. 2022 v 4:44 odesílatel Jason Liu ***@***.***>
napsal:

> From postgresql12.9,when 'session_exec' call a function like behind, will
> output a log "cannot execute SQL without an outer snapshot or portal", and
> the function can't execute.
>
> create or replace function public.login() returns void as $$
> declare
> res record;
> n_times constant int := 10;
> failed_login_times constant int := 5;
> failed_login integer;
> begin
> end;
> $$ language plpgsql strict security definer set search_path to 'public';
>
Should be fixed. Please, check it.
